#!/usr/bin/env node
/**
 * Hebrew social graphics for Shaio Media.
 *
 *   node render.mjs render posts/*.json          → out/<id>-<size>.png
 *   node render.mjs capture <url> <name>         → assets/<name>.webp (a "before" shot)
 *
 * Text is real DOM text in Rubik, never generated by an image model: no
 * diffusion model renders Hebrew that a native reader will accept.
 */
import { readFileSync, writeFileSync, mkdirSync, existsSync, readdirSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, resolve, join, basename, extname } from 'node:path';
import { page } from './templates.mjs';
import { sizes } from './brand.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const OUT = join(HERE, 'out');
const ASSETS = join(HERE, 'assets');

/* Playwright may live in the project or only in the npx cache. Try both before
   telling the user to install, so the tool works on a clean checkout. */
async function chromium() {
  const candidates = [
    'playwright',
    '/Users/shayeini/.npm/_npx/705bc6b22212b352/node_modules/playwright',
  ];
  for (const c of candidates) {
    try { return (await import(c)).chromium; } catch { /* next */ }
  }
  throw new Error('playwright not found. run: npm i playwright  (inside social/)');
}

/* ---------- fonts ---------- */

/** Inline Rubik as base64 so a render never depends on the network or on
 *  whatever happens to be installed on the machine. */
function fontCss() {
  const dir = join(ROOT, 'node_modules/@fontsource-variable/rubik/files');
  const face = (file, range) => {
    const b64 = readFileSync(join(dir, file)).toString('base64');
    return `@font-face{font-family:"Rubik";font-style:normal;font-weight:100 900;font-display:block;` +
           `src:url(data:font/woff2;base64,${b64}) format("woff2");unicode-range:${range};}`;
  };
  return [
    face('rubik-hebrew-wght-normal.woff2', 'U+0590-05FF,U+200C-2010,U+20AA,U+25CC,U+FB1D-FB4F'),
    face('rubik-latin-wght-normal.woff2', 'U+0000-00FF,U+0131,U+0152-0153,U+2000-206F,U+2074,U+20AC,U+2122,U+2212'),
  ].join('\n');
}

/* ---------- asset paths ---------- */

/** `@pwcroofing` → the mobile capture of that client's live site.
 *  Anything else is resolved against the repo root, then handed over as file://
 *  because the page is loaded from a temp file, not a server. */
function asset(p) {
  if (!p) return p;
  if (/^https?:\/\//.test(p)) return p;
  if (p.startsWith('@')) {
    const slug = p.slice(1);
    for (const cand of [
      join(ROOT, `public/images/sites/${slug}-mobile.webp`),
      join(ASSETS, `${slug}.webp`),
      join(ASSETS, `${slug}.png`),
    ]) if (existsSync(cand)) return pathToFileURL(cand).href;
    throw new Error(`no asset for ${p}`);
  }
  const abs = resolve(ROOT, p);
  if (!existsSync(abs)) throw new Error(`missing asset: ${p}`);
  return pathToFileURL(abs).href;
}

const IMAGE_KEYS = ['before', 'after', 'image'];
function resolveAssets(spec) {
  const out = { ...spec };
  for (const k of IMAGE_KEYS) if (out[k]) out[k] = asset(out[k]);
  return out;
}

/* ---------- render ---------- */

async function render(files) {
  mkdirSync(OUT, { recursive: true });
  const css = fontCss();
  const logo = pathToFileURL(join(ROOT, 'public/logo-white.webp')).href;
  const logoDark = pathToFileURL(join(ROOT, 'public/logo.webp')).href;

  const browser = await (await chromium()).launch();
  const tmp = join(OUT, '.render.html');
  let n = 0;

  for (const file of files) {
    const raw = JSON.parse(readFileSync(file, 'utf8'));
    const specs = Array.isArray(raw) ? raw : [raw];

    for (const s0 of specs) {
      const spec = resolveAssets(s0);
      const id = spec.id ?? basename(file, extname(file));
      const wanted = spec.sizes ?? ['feed'];

      for (const size of wanted) {
        const dim = sizes[size];
        if (!dim) throw new Error(`unknown size: ${size}`);

        // 2x so the PNG survives Instagram's re-compression.
        const ctx = await browser.newContext({
          viewport: { width: dim.w, height: dim.h },
          deviceScaleFactor: 2,
        });
        const pg = await ctx.newPage();
        writeFileSync(tmp, page(spec, {
          fontCss: css,
          logo: spec.theme === 'light' ? logoDark : logo,
          size,
        }));
        await pg.goto(pathToFileURL(tmp).href, { waitUntil: 'load' });
        await pg.evaluate(() => document.fonts.ready);
        const out = join(OUT, `${id}-${size}.png`);
        await pg.screenshot({ path: out });
        await ctx.close();
        console.log(`  ${basename(out)}  ${dim.w}x${dim.h} @2x`);
        n++;
      }
    }
  }
  await browser.close();
  console.log(`\n${n} graphic(s) → social/out/`);
}

/* ---------- capture ---------- */

/** Screenshot any live site as a phone-shaped "before". This is what makes the
 *  cold outreach post possible: the prospect's current site, as it is today. */
async function capture(url, name) {
  mkdirSync(ASSETS, { recursive: true });
  const browser = await (await chromium()).launch();
  const ctx = await browser.newContext({
    viewport: { width: 430, height: 932 },
    deviceScaleFactor: 3,
    isMobile: true,
    hasTouch: true,
    userAgent: 'Mozilla/5.0 (iPhone; CPU iPhone OS 17_0 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.0 Mobile/15E148 Safari/604.1',
  });
  const pg = await ctx.newPage();
  await pg.goto(url, { waitUntil: 'networkidle', timeout: 60_000 }).catch(() => {});
  await pg.waitForTimeout(2500);
  const out = join(ASSETS, `${name}.png`);
  await pg.screenshot({ path: out, fullPage: false });
  await browser.close();
  console.log(`captured → social/assets/${name}.png`);
}

/* ---------- cli ---------- */

const [cmd, ...rest] = process.argv.slice(2);

if (cmd === 'render') {
  let files = rest;
  if (!files.length) {
    const dir = join(HERE, 'posts');
    files = readdirSync(dir).filter((f) => f.endsWith('.json')).map((f) => join(dir, f));
  }
  await render(files);
} else if (cmd === 'capture') {
  const [url, name] = rest;
  if (!url || !name) { console.error('usage: capture <url> <name>'); process.exit(1); }
  await capture(url, name);
} else {
  console.log(`usage:
  node render.mjs render [posts/*.json]   render graphics (default: all of posts/)
  node render.mjs capture <url> <name>    screenshot a live site as a "before"`);
}
